### ISSUE TITLE
Version clash of gulp-dr-frankenstyle

### ISSUE THREAD

**Issue by benmoss** [pivotal-cf-experimental/xray#5]
Doing an `npm install` yields: `npm WARN package.json Dependency 'gulp-dr-frankenstyle' exists in both dependencies and devDependencies, using 'gulp-dr-frankenstyle@0.0.5' from dependencies`.

That version of the package seems to have a bad dependency specification on the underlying dr-frankenstyle package and crashes when you run `gulp assets-all` with 

```
Error: Cannot find module 'dr-frankenstyle/lib/strategies'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/pivotal/workspace/xray/node_modules/gulp-dr-frankenstyle/index.js:4:23)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pivotal/workspace/xray/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:136:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by rdy** [comment]
fixed in master
